# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pruebaCI

on:
  push:
    branches: [ pruebasCI ]
  pull_request:
    branches: [ pruebasCI ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Instalar dependencias
        run: yarn --frozen-lockfile
      - run: yarn run build
